homes = [

    {

        "id": 0,
        "title": "Villa i Vejle",
        "city": "Vejle",
        "price": 2800000,
        "size": 150,
        "rooms": 4,
        "energy": "A",
        "near_shopping": True,
        "garage": True,
        "garden": True,
        "forest_nearby": False,
        "image": "images/house0.jpg",
        "commute_score": 7,
        "family_score": 8,
        "investment_score": 6,

    },

    {

        "id": 1,
        "title": "Familiehus i Vejle",
        "city": "Vejle",
        "price": 3100000,
        "size": 165,
        "rooms": 5,
        "energy": "B",
        "near_shopping": True,
        "garage": True,
        "garden": True,
        "forest_nearby": True,
        "image": "images/house1.jpg",
        "commute_score": 8,
        "family_score": 9,
        "investment_score": 7,

    },

    {

        "id": 2,
        "title": "Byhus i Aarhus",
        "city": "Aarhus",
        "price": 2600000,
        "size": 110,
        "rooms": 3,
        "energy": "B",
        "near_shopping": True,
        "garage": False,
        "garden": False,
        "forest_nearby": False,
        "image": "images/house2.jpg",
        "commute_score": 9,
        "family_score": 5,
        "investment_score": 8,

    },

    {

        "id": 3,
        "title": "Naturvilla i Silkeborg",
        "city": "Silkeborg",
        "price": 3350000,
        "size": 215,
        "rooms": 6,
        "energy": "C",
        "near_shopping": False,
        "garage": False,
        "garden": True,
        "forest_nearby": True,
        "image": "images/house3.jpg",
        "commute_score": 6,
        "family_score": 8,
        "investment_score": 6,

    },

    {
        "id": 4,
        "title": "Arkitektvilla i Horsens",
        "city": "Horsens",
        "price": 3200000,
        "size": 245,
        "rooms": 7,
        "energy": "C",
        "near_shopping": True,
        "garage": True,
        "garden": True,
        "forest_nearby": False,
        "image": "images/house4.jpg",
        "commute_score": 7,
        "family_score": 8,
        "investment_score": 6,
    },
    {
        "id": 5,
        "title": "Rækkehus i Vejle centrum",
        "city": "Vejle",
        "price": 2350000,
        "size": 120,
        "rooms": 4,
        "energy": "A",
        "near_shopping": True,
        "garage": False,
        "garden": True,
        "forest_nearby": False,
        "image": "images/house5.jpg",
        "commute_score": 9,
        "family_score": 6,
        "investment_score": 7,
    },
    {
        "id": 6,
        "title": "Skovvilla ved Silkeborg søerne",
        "city": "Silkeborg",
        "price": 3400000,
        "size": 225,
        "rooms": 6,
        "energy": "B",
        "near_shopping": False,
        "garage": True,
        "garden": True,
        "forest_nearby": True,
        "image": "images/house6.jpg",
        "commute_score": 6,
        "family_score": 7,
        "investment_score": 8,
    },
    {
        "id": 7,
        "title": "Familievilla tæt på naturen i Vejle",
        "city": "Vejle",
        "price": 3950000,
        "size": 195,
        "rooms": 6,
        "energy": "C",
        "near_shopping": False,
        "garage": False,
        "garden": True,
        "forest_nearby": True,
        "image": "images/house7.jpg",
        "commute_score": 8,
        "family_score": 9,
        "investment_score": 7,
    },
    {

       "id": 8,

       "title": "Modern villa i Aarhus",
       "price": 4350000,
       "city": "Aarhus",
       "size": 180,
       "rooms": 5,
       "energy": "B",
       "near_shopping": True,
       "garage": True,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house8.jpg",
       "commute_score": 9,
       "family_score": 6,
       "investment_score": 7,
    },
    {

       "id": 9,

       "title": "Rækkehus i Odense",
       "price": 2600000,
       "city": "Odense",
       "size": 160,
       "rooms": 4,
       "energy": "D",
       "near_shopping": True,
       "garage": True,
       "garden": False,
       "forest_nearby": False,
       "image": "images/house9.jpg",
       "commute_score": 7,
       "family_score": 8,
       "investment_score": 7,
    },
    {

       "id": 10,

       "title": "Landejendom nær Herning",
       "price": 3900000,
       "city": "Herning",
       "size": 250,
       "rooms": 8,
       "energy": "D",
       "near_shopping": False,
       "garage": True,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house10.jpg",
       "commute_score": 8,
       "family_score": 8,
       "investment_score": 7,
    },
    {

       "id": 11,

       "title": "Lejlighed i København",
       "price": 5200000,
       "city": "København",
       "size": 130,
       "rooms": 4,
       "energy": "B",
       "near_shopping": True,
       "garage": False,
       "garden": False,
       "forest_nearby": True,
       "image": "images/house11.jpg",
       "commute_score": 7,
       "family_score": 8,
       "investment_score": 6,
    },
    {

       "id": 12,

       "title": "Villa i Kolding",
       "price": 2900000,
       "city": "Kolding",
       "size": 170,
       "rooms": 4,
       "energy": "C",
       "near_shopping": True,
       "garage": True,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house12.jpg",
       "commute_score": 6,
       "family_score": 9,
       "investment_score": 6,
    },
    {

       "id": 13,

       "title": "Nybyg i Silkeborg",
       "price": 4100000,
       "city": "Silkeborg",
       "size": 200,
       "rooms": 6,
       "energy": "A",
       "near_shopping": False,
       "garage": True,
       "garden": True,
       "forest_nearby": True,
       "image": "images/house13.jpg",
       "commute_score": 7,
       "family_score": 7,
       "investment_score": 9,
    },
    {

       "id": 14,

       "title": "Charmerende hus i Horsens",
       "price": 2400000,
       "city": "Horsens",
       "size": 160,
       "rooms": 4,
       "energy": "D",
       "near_shopping": True,
       "garage": True,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house14.jpg",
       "commute_score": 8,
       "family_score": 8,
       "investment_score": 5,
    },
    {

       "id": 15,

       "title": "Familievilla i Randers",
       "price": 2350000,
       "city": "Randers",
       "size": 185,
       "rooms": 6,
       "energy": "C",
       "near_shopping": True,
       "garage": False,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house15.jpg",
       "commute_score": 6,
       "family_score": 9,
       "investment_score": 7,
    },
    {

       "id": 16,

       "title": "Luksus villa i Aalborg",
       "price": 4800000,
       "city": "Aalborg",
       "size": 215,
       "rooms": 7,
       "energy": "A",
       "near_shopping": True,
       "garage": True,
       "garden": True,
       "forest_nearby": False,
       "image": "images/house16.jpg",
       "commute_score": 9,
       "family_score": 7,
       "investment_score": 7,
    },
    {

      "id": 17,

      "title": "Sommerhus i Blåvand",
      "price": 3200000,
      "city": "Blåvand",
      "size": 150,
      "rooms": 3,
      "energy": "E",
      "near_shopping": False,
      "garage": False,
      "garden": True,
      "forest_nearby": True,
      "image": "images/house17.jpg",
      "commute_score": 6,
      "family_score": 7,
      "investment_score": 9,
    },
    {

      "id": 18,

      "title": "Byhus i Esbjerg",
      "price": 2300000,
      "city": "Esbjerg",
      "size": 160,
      "rooms": 4,
      "energy": "C",
      "near_shopping": True,
      "garage": False,
      "garden": True,
      "forest_nearby": False,
      "image": "images/house18.jpg",
      "commute_score": 7,
      "family_score": 7,
      "investment_score": 9,
    },
    {

      "id": 19,

      "title": "Villa i Fredericia",
      "price": 2800000,
      "city": "Fredericia",
      "size": 160,
      "rooms": 6,
      "energy": "A",
      "near_shopping": True,
      "garage": True,
      "garden": True,
      "forest_nearby": True,
      "image": "images/house19.jpg",
      "commute_score": 8,
      "family_score": 6,
      "investment_score": 8,
    }
]